config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :books do
    resources :reviews, except: [:show, :index]
  end

  root 'books#index'
end

app/models/book.rb
class Book < ActiveRecord::Base

  validates :title, presence: true
  validates :pages, numericality: { only_integer: true }
  has_attached_file :cover, :styles => { :medium => '400x400>', :thumb => '200x200>' },
                  :default_url => '/images/:style/missing.png'
  validates_attachment_content_type :cover, :content_type => /\Aimage\/.*\Z/
  validates_attachment_presence :cover

  belongs_to :user  
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :books         
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @books = Book.all
  end

  def show
    @reviews = Review.where(book_id: @book.id).order("created_at DESC")
    
    if @reviews.blank?
      @avg_review = 0
    else
      @avg_review = @reviews.average(:rating).round(2)
    end
  end

  def new
    @book = current_user.books.build
  end

  def create
    @book = current_user.books.build(book_params)
    if @book.save
      redirect_to @book, notice: 'Book added to your base!' 
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: 'Book successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @book.destroy
    redirect_to books_url, notice: 'Book was successfully deleted.'
  end

  private
    def book_params
      params.require(:book).permit(:title, :author, :pages, :cover)
    end

    def set_book
      @book = Book.find(params[:id])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_book
  before_action :authenticate_user! 

  def new
    @review = current_user.reviews.build
  end

  def edit
  end

  def create
    @review = current_user.reviews.build(review_params)
    @review.book_id = @book.id
    
    if @review.save
      redirect_to @book, notice: 'Review was successfully created.'  
    else
      render 'new'
    end
  end

  def update
    if @review.update(review_params)
      redirect_to @book, notice: 'Review was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy
    redirect_to book_url, notice: 'Review was successfully destroyed.'
  end

  private
    def set_review
      @review = Review.find(params[:id])
    end
    
    def set_book
      @book = Book.find(params[:book_id])
    end

    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_form.html.erb
<%= form_for @book, html: { multipart: true } do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :pages %><br>
    <%= f.number_field :pages %>
  </div>
  <div class="field">
    <%= f.label :cover %><br>
    <%= f.file_field :cover %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<%= provide(:title, @book.title) %>
<h1>Edit Book</h1>

<%= render 'form' %>

app/views/books/index.html.erb
<%= provide(:title, 'Books') %>

<% if !user_signed_in? %>
  <div class="jumbotron">
    <h1>Books You Read</h1>
    <p>Create your own bookshelf. Track and review books you read or you want to read.</p>
    <p><%= link_to "Sign Up To Create Your Bookshelf", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
  </div>
<% end %>

<div class="row">
  <% @books.each do |book| %>
    <div class="col-sm-6 col-md-3">
      <div class="thumbnail">
        <%= link_to (image_tag book.cover.url(:medium), class: 'image'), book %>
      </div>
    </div>
  <% end %>
</div>

app/views/books/new.html.erb
<%= provide(:title, 'Add Book') %>
<h1>Add Book</h1>

<%= render 'form' %>

app/views/books/show.html.erb
<%= provide(:title, @book.title) %>

<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @book.cover.url(:medium) %>
        <div class="star-rating" data-score= <%= @avg_review %> ></div>
        <em><%= "#{@reviews.length} reviews" %></em>
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td><strong>Title:</strong></td>
                <td><%= @book.title %></td>
              </tr>
              <tr>
                <td><strong>Pages:</strong></td>
                <td><%= @book.pages %></td>
              </tr>
            </tbody>
          </table>
          <%= link_to "Write a Review", new_book_review_path(@book) %>
        </div>
      </div>
      <div class="col-md-7 col-md-offset-1">
        <h1 class="review_title"><%= @book.title %></h1>

        <% if @reviews.blank? %>
          <h3>No reviews just yet, would you like to add the first!</h3>
          <%= link_to "Write Review", new_book_review_path(@book), class: "btn btn-danger" %>
        <% else %>
          <% @reviews.each do |review| %>
            <div class="reviews">
              <div class="star-rating" data-score= <%= review.rating %> ></div>
              <p><%= review.comment %></p>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Books", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "New Book", new_book_path, class: "active" %></li>
          <li><%= link_to "Account", edit_user_registration_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
		  <li>
		  <%= link_to('Sign Out', destroy_user_session_path, :method => :delete) %>        
		  </li>
		<% else %>
		  <li>
		  <%= link_to('Sign In', new_user_session_path)  %>  
		  </li>
		<% end %>
     </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	<title><%= yield(:title) %></title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/reviews/_form.html.erb
<%= form_for [@book, @review] do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div id="star-rating"></div>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Back', book_path(@book) %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', book_path(@book) %>